### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by infobalu** [mahavirsinghr/Java-Spring-Boot-MyBatis-Angular#1]
http://localhost:9095/ url returns below error

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Sep 25 19:06:19 IST 2018
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by mahavirsinghr** [comment]
I will send you screenshots tomorrow

**Comment by mahavirsinghr** [comment]
You are missing slash endpoints name

Please type endpoints name

**Comment by infobalu** [comment]
Could you please share end name.

**Comment by mahavirsinghr** [comment]
I had resolved closing unresolved ticket

**Comment by infobalu** [comment]
Ok thank you.
